# Embedding Models Configuration

model = "qwen3-embedding"

[models.qwen3-embedding]
name = "text-embedding-v4"
dimensions = 2048
type = "openai-compatible"
api_endpoint = "https://dashscope.aliyuncs.com/compatible-mode/v1"
max_tokens = 8192
max_batch_size = 10
api_key_env = "ALIYUN_KEY"
